// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SOUL_HMCustomizer","status":true,"description":"A customizable simple menu for horror games. Version 2.0","parameters":{"Actor Bust Picture":"Collabo2_1","Actor Bust X":"0","Actor Bust Y":"0","Menu Command X":"250","Menu Command Y":"120","Options Window X":"200","Options Window Y":"300","GameEnd Window X":"500","GameEnd Window Y":"200"}}
];
